[tool.pyright]
include = ["ssd", "experiments", "tests"]
exclude = ["**/node_modules", "**/__pycache__"]

reportMissingImports = "error"
reportMissingTypeStubs = true

pythonVersion = "3.12"
pythonPlatform = "Linux"
venv = ".venv"
venvPath = "."
